#!/bin/bash
#
# Archaic Configuration Wizard
# Interactive setup for first-time users
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_banner() {
    echo -e "${BLUE}"
    cat << 'EOF'
    _                _     _
   / \   _ __  _ __ | |__ (_) __ _ _ __ ___
  / _ \ | '_ \| '_ \| '_ \| |/ _` | '_ ` _ \
 / ___ \| | | | | | | | | | | (_| | | | | | |
/_/   \_\_| |_|_| |_|_| |_|_|\__,_|_| |_| |_|

EOF
    echo -e "${NC}"
    echo "Interactive Configuration Wizard"
    echo "================================"
    echo
}

ask() {
    local prompt="$1"
    local default="$2"
    local response

    if [ -n "$default" ]; then
        read -rp "$prompt [$default]: " response
        echo "${response:-$default}"
    else
        read -rp "$prompt: " response
        echo "$response"
    fi
}

ask_yes_no() {
    local prompt="$1"
    local default="${2:-y}"
    local response

    while true; do
        read -rp "$prompt [Y/n]: " response
        response="${response:-$default}"
        case "$response" in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

detect_shell() {
    if [ -n "$SHELL" ]; then
        basename "$SHELL"
    else
        echo "unknown"
    fi
}

find_scan_path() {
    local common_paths=(
        "$HOME/projects"
        "$HOME/workspace"
        "$HOME/code"
        "$HOME/src"
        "$HOME/dev"
        "$HOME/work"
        "$HOME"
    )

    for path in "${common_paths[@]}"; do
        if [ -d "$path" ]; then
            echo "$path"
            return
        fi
    done

    echo "$HOME"
}

generate_config() {
    local scan_path="$1"
    local socket_path="$2"
    local scan_threads="$3"
    local max_depth="$4"
    local colored_output="$5"
    local case_insensitive="$6"
    local recent_capacity="$7"

    cat << EOF
# Archaic Configuration
# Generated by configuration wizard on $(date)

[daemon]
scan_path = "$scan_path"
socket_path = "$socket_path"
scan_threads = $scan_threads
max_depth = $max_depth
rescan_interval_seconds = 300

[storage]
max_buckets = 65536
max_nodes_per_bucket = 100000
cache_max_entries = 1024
cache_ttl_seconds = 2
colored_output = $colored_output
case_insensitive = $case_insensitive
recent_files_capacity = $recent_capacity

[scoring]
weight_frequency = 0.40
weight_recency = 0.30
weight_depth = 0.15
weight_type = 0.10
weight_cwd_proximity = 0.05

[fish]
commands = ["cd", "ls", "cat", "vim", "nvim", "less", "bat", "rm", "mv", "cp", "mkdir", "touch"]

[bash]
commands = ["cd", "ls", "cat", "vim", "nvim", "less", "bat", "rm", "mv", "cp", "mkdir", "touch"]

[zsh]
commands = ["cd", "ls", "cat", "vim", "nvim", "less", "bat", "rm", "mv", "cp", "mkdir", "touch"]

[scanner]
ignore_dirs = [".git", "node_modules", "build", "dist", "__pycache__", ".venv", ".idea", ".vscode"]
ignore_files = ["*.pyc", "*.o", "*.log", ".DS_Store", "*.tmp", "*.swp"]
EOF
}

install_shell_integration() {
    local shell="$1"

    case "$shell" in
        fish)
            if [ -d "$HOME/.config/fish" ]; then
                echo -e "${GREEN}Installing Fish integration...${NC}"
                cp "$REPO_ROOT/fish/archaic.fish" "$HOME/.config/fish/conf.d/"
                echo -e "${GREEN}✓ Fish integration installed${NC}"
            else
                echo -e "${YELLOW}Fish config directory not found. Skipping.${NC}"
            fi
            ;;
        bash)
            local bash_completion_dir="$HOME/.local/share/bash-completion/completions"
            mkdir -p "$bash_completion_dir"
            echo -e "${GREEN}Installing Bash integration...${NC}"
            cp "$REPO_ROOT/bash/archaic.bash" "$bash_completion_dir/archaic"
            echo -e "${GREEN}✓ Bash integration installed${NC}"
            echo -e "${YELLOW}Note: Add this to your ~/.bashrc:${NC}"
            echo "source ~/.local/share/bash-completion/completions/archaic"
            ;;
        zsh)
            local zsh_dir="$HOME/.config/zsh"
            mkdir -p "$zsh_dir"
            echo -e "${GREEN}Installing Zsh integration...${NC}"
            cp "$REPO_ROOT/zsh/archaic.zsh" "$zsh_dir/"
            echo -e "${GREEN}✓ Zsh integration installed${NC}"
            echo -e "${YELLOW}Note: Add this to your ~/.zshrc:${NC}"
            echo "source ~/.config/zsh/archaic.zsh"
            ;;
        *)
            echo -e "${YELLOW}Unknown shell: $shell. Skipping integration.${NC}"
            ;;
    esac
}

main() {
    print_banner

    echo -e "${BLUE}Step 1: Scan Path Configuration${NC}"
    echo "This is the directory Archaic will index for completions."
    echo

    local default_scan_path
    default_scan_path=$(find_scan_path)
    SCAN_PATH=$(ask "Directory to scan" "$default_scan_path")

    if [ ! -d "$SCAN_PATH" ]; then
        echo -e "${RED}Error: Directory does not exist: $SCAN_PATH${NC}"
        exit 1
    fi

    echo
    echo -e "${BLUE}Step 2: Performance Configuration${NC}"
    echo

    local cpu_count
    cpu_count=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)
    local default_threads=$((cpu_count > 4 ? 4 : cpu_count))

    SCAN_THREADS=$(ask "Number of scan threads (1-8)" "$default_threads")
    MAX_DEPTH=$(ask "Maximum directory depth (5-20)" "10")

    echo
    echo -e "${BLUE}Step 3: Feature Configuration${NC}"
    echo

    if ask_yes_no "Enable colored output?" "y"; then
        COLORED_OUTPUT="true"
    else
        COLORED_OUTPUT="false"
    fi

    if ask_yes_no "Enable case-insensitive matching?" "n"; then
        CASE_INSENSITIVE="true"
    else
        CASE_INSENSITIVE="false"
    fi

    RECENT_CAPACITY=$(ask "Recent files list capacity (10-100)" "50")

    echo
    echo -e "${BLUE}Step 4: Shell Integration${NC}"
    echo

    local current_shell
    current_shell=$(detect_shell)
    echo "Detected shell: $current_shell"
    echo

    local install_fish=false
    local install_bash=false
    local install_zsh=false

    if [ "$current_shell" = "fish" ] || ask_yes_no "Install Fish shell integration?" "n"; then
        if [ "$current_shell" = "fish" ]; then
            install_fish=true
        elif ask_yes_no "Install Fish integration?" "n"; then
            install_fish=true
        fi
    fi

    if [ "$current_shell" = "bash" ] || ask_yes_no "Install Bash integration?" "n"; then
        if [ "$current_shell" = "bash" ]; then
            install_bash=true
        elif ask_yes_no "Install Bash integration?" "n"; then
            install_bash=true
        fi
    fi

    if [ "$current_shell" = "zsh" ] || ask_yes_no "Install Zsh integration?" "n"; then
        if [ "$current_shell" = "zsh" ]; then
            install_zsh=true
        elif ask_yes_no "Install Zsh integration?" "n"; then
            install_zsh=true
        fi
    fi

    echo
    echo -e "${BLUE}Step 5: Configuration Summary${NC}"
    echo
    echo "Scan path: $SCAN_PATH"
    echo "Threads: $SCAN_THREADS"
    echo "Max depth: $MAX_DEPTH"
    echo "Colored output: $COLORED_OUTPUT"
    echo "Case insensitive: $CASE_INSENSITIVE"
    echo "Recent files capacity: $RECENT_CAPACITY"
    echo

    if ! ask_yes_no "Save this configuration?" "y"; then
        echo -e "${YELLOW}Configuration cancelled.${NC}"
        exit 0
    fi

    mkdir -p "$HOME/.config/archaic"

    SOCKET_PATH="/tmp/archaic-daemon.sock"
    generate_config "$SCAN_PATH" "$SOCKET_PATH" "$SCAN_THREADS" "$MAX_DEPTH" \
        "$COLORED_OUTPUT" "$CASE_INSENSITIVE" "$RECENT_CAPACITY" \
        > "$HOME/.config/archaic/config.toml"

    echo -e "${GREEN}✓ Configuration saved to ~/.config/archaic/config.toml${NC}"

    if [ "$install_fish" = true ]; then
        install_shell_integration "fish"
    fi
    if [ "$install_bash" = true ]; then
        install_shell_integration "bash"
    fi
    if [ "$install_zsh" = true ]; then
        install_shell_integration "zsh"
    fi

    echo
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}Configuration complete!${NC}"
    echo -e "${GREEN}================================${NC}"
    echo
    echo "Next steps:"
    echo "  1. Start the daemon: ./run.sh start $SCAN_PATH"
    echo "  2. Restart your shell or source the integration script"
    echo "  3. Try tab completion with: cd <TAB>"
    echo
    echo "For more options, edit ~/.config/archaic/config.toml"
}

main "$@"
